apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: blame
spec:
  version: {{ .TagName }}
  homepage: https://github.com/knight42/kubectl-blame
  shortDescription: Show the manager of each field of given resource with information from managed fields.
  description: |
    Annotate each line in the given resource's YAML with information from the managedFields to show who last modified the field.

    Examples:

    # Blame pod 'foo' in default namespace
    kubectl blame pods foo

    # Blame deployment 'bar' in 'ns1' namespace
    kubectl blame -n ns1 deploy bar
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/knight42/kubectl-blame/releases/download/{{ .TagName }}/kubectl-blame-{{ .TagName }}-darwin-amd64.tar.gz" .TagName }}
    bin: kubectl-blame
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/knight42/kubectl-blame/releases/download/{{ .TagName }}/kubectl-blame-{{ .TagName }}-linux-amd64.tar.gz" .TagName }}
    bin: kubectl-blame
